### ISSUE TITLE
Make a banner

### ISSUE THREAD

**Issue by m1guelpf** [m1guelpf/Activity#19]
We need a banner for the Activity project.
It will be located at the top of our github README and the creator will be credited in the Credits section.
It should be simple, contain the word Activity and the logo.
This is an awesome oportunity for newcomers to start working on a Github project!

**Comment by usmanatron** [comment]
Happy to have a go at this @m1guelpf :-)
Just to make sure I understand exactly what you're after, can you please point me in the direction of an example from another project?  The README.md file already appears to have something...

Ta
Usman

**Comment by m1guelpf** [comment]
@usmanatron What we have now is a logo in the top of the README.md
I would like a little banner showcasing the functionality of the script and/or how does it work and/or the features and/or a GIT showing the script working...

**Comment by usmanatron** [comment]
@m1guelpf Thanks for the explanation.
I think I now understand what you're after.  I'll have a go :-)
